name: meditation
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  image_cropper: ^7.0.5
  cached_network_image: ^3.3.1
  step_progress_indicator: ^1.0.2
  glassmorphism: ^3.0.0
  flutter_time_picker_spinner: ^2.0.0
  get_storage: ^2.1.1
  stop_watch_timer: ^3.1.1
  lottie: ^3.1.2
  assets_audio_player: ^3.1.1
  date_time_picker_widget: ^2.0.0
  flutter_neumorphic: ^3.2.0
  audio_video_progress_bar: ^2.0.3
  share_plus: ^9.0.0
  flutter_phoenix: ^1.1.1
  flutter_slidable: ^3.1.0
  image_picker: ^1.1.2
  glass_kit: ^4.0.1
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1

  flutter_localizations:
    sdk: flutter
#  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.0
  provider: ^6.1.2
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.1
  logger: ^2.3.0
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  percent_indicator: ^4.2.3
  pull_to_refresh_flutter3: ^2.0.2
  onesignal_flutter: ^5.2.0
  google_mobile_ads: ^5.1.0
  flutter_html: ^3.0.0-beta.2

  path: any
  path_provider: any
  sqflite: any
  intl: any
dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1


  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.19.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo/Meditation_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/Lottie/
    - assets/Logo/
#    - assets/newicons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Meditation.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true